# Lode Runner Pattern-Based Problem Configuration
problem:
  name: "loderunner-patterns-v0"
  class: "LodeRunnerProblem"
  
# Level generation parameters
level:
  width: 22  # Doubled from pattern size
  height: 16  # Doubled from pattern size
  
# Pattern-specific parameters
patterns:
  base_width: 11  # Pattern grid width
  base_height: 8  # Pattern grid height
  
# Game-specific parameters
game:
  gold: 8
  enemies: 3
  exploration: 0.2
  islands: 0.1
  decorations: 0.75
  used_tiles: 0.75
  diversity: 0.4
  
# Rendering parameters
rendering:
  scale: 16
  
# Tile types (for reference)
tiles:
  brick: 0
  empty: 1
  player: 2
  gold: 3
  enemy: 4
  ladder: 5
  rope: 6