# Building Problem Configuration - Large Version
problem:
  name: "building-large-v0"
  class: "BuildingProblem"
  
# Level generation parameters
level:
  width: 11
  length: 11
  height: 12
  
# Game-specific parameters
game:
  blocks: 180
  minHeight: 0.4
  diversity: 0.4
  
# Rendering parameters
rendering:
  scale_x: 16
  scale_y: 8
  
# Block types (for reference)
blocks:
  "1x1": 0
  "1x3": 1
  "3x1": 2
  "3x3": 3