algo: DQN
total_steps: 10000000
replay_size: 200000
batch_size: 4096
start_learning: 10000
target_update: 10000
learning_rate: 0.0003
eps_start: 1.0
eps_end: 0.05
eps_decay: 500000
gamma: 0.99
eval_episodes: 50
checkpoint_interval: 50000
do_pretrain: false


pretrain:
  fail_fast: true
  hooks:
    - name: "obs_norm_fit_5k"
      type: "fit_obs_norm"
      order: 10
      enabled: true
      config:
        steps: 5000

    - name: "bc_warmstart"
      type: "behavior_cloning"
      order: 20
      enabled: false    # flip to true if you have demos
      config:
        dataset: "/path/to/demos.npz"
        epochs: 5
        batch_size: 256
        lr: 3e-4

    - name: "sanity_eval"
      type: "eval_sanity"
      order: 90
      enabled: true
      config:
        episodes: 3